baseURL = "https://nchlswhttkr.github.io/hacktoberfest-2019/"
languageCode = "en-us"
title = "Hacktoberfest"
theme = "minimal-bootstrap-hugo-theme"
enableEmoji = "true"
pygmentsCodeFences = "true"

[params]
    customDateFormat = " "
    wrapperMaxWidth = "700px"
    includeBootstrapJs = "false"

[menu]
    [[menu.nav]]
    name = "Participants"
    url = "/"
    weight = 1
    [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 2
    [[menu.nav]]
    name = "Contribute!"
    url = "/contribute/"
    weight = 2
    [[menu.nav]]
    name = "GitHub"
    url = "https://github.com/nchlswhttkr/hacktoberfest-2019"
    weight = 3